# Generated by Django 2.2.1 on 2019-05-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='topic_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='trending',
            name='content',
            field=models.TextField(default='aaaa'),
            preserve_default=False,
        ),
    ]
